%%% Algebraic Solutions 

%% Profit maximization

syms xi_1_t xi_1_s xi_2_t xi_2_s p_1 p_2 p_t p_s x_1 x_2

[x_1_prof, x_2_prof] = solve(p_t*xi_1_t + p_s*xi_1_s - 2*p_1*x_1 == 0 ,...
                           p_t*xi_2_t + p_s*xi_2_s - 2*p_2*x_2 == 0, x_1, x_2)
                       

%% Utility max

[x_1_util, x_2_util] = solve( ...
    p_t == (alpha*budget)/(xi_1_t*x_1 + xi_2_t*x_2), ...
    p_s == (beta*budget)/(xi_1_s*x_1 + xi_2_s*x_2), ...
    ...%(alpha*budget)*(xi_1_t./(xi_1_t*x_1 + xi_2_t*x_2)) + (beta*budget)*(xi_1_s./(xi_1_s*x_1 + xi_2_s*x_2)) == 0, ...
    ...%(alpha*budget)*(xi_2_t./(xi_1_t*x_1 + xi_2_t*x_2)) + (beta*budget)*(xi_2_s./(xi_1_s*x_1 + xi_2_s*x_2)) == 0, ...
    (xi_1_t*x_1 + xi_2_t*x_2)*p_t + (xi_1_s*x_1 + xi_2_s*x_2)*p_s == budget, x_1, x_2)
    


                       
%% Central Planner Welfare maximization

syms alpha beta budget y_t y_s

[x_1_cent, x_2_cent] = solve(...
    (alpha*budget)*(xi_1_t/(xi_1_t*x_1 + xi_2_t*x_2)) + (beta*budget)*(xi_1_s/(xi_1_s*x_1 + xi_2_s*x_2)) + ...
    p_t*xi_1_t + p_s*xi_1_s - 2*p_1*x_1 == 0,  ...
    (alpha*budget)*(xi_2_t/(xi_1_t*x_1 + xi_2_t*x_2)) + (beta*budget)*(xi_2_s/(xi_1_s*x_1 + xi_2_s*x_2)) + ...
    p_t*xi_2_t + p_s*xi_2_s - 2*p_2*x_2 == 0 ...
          )

      